export const TASKS = [
  {
    id: 1,
    status: "New Order",
    color:"red",
    time: "Project A",
    days: "2",
  },
  {
    id: 2,
    status: "In Progress",
    color:"blue",
    time: "Project B",
    days: "6",
    done: false,
  },
  {
    id: 3,
    status: "Completed",
    color:"green",
    time: "Project W",
    days: "4",
  },
  {
    id: 4,
    status: "New Order",
    color:"purple",
    time: "Project X",
    days: "2",
    done: true,
  },
  {
    id: 5,
    status: "In Progress",
    color:"grey",
    time: "Project T",
    days: " ",
    newOrder: true,
    done: false,
  },
  {
    id: 6,
    status: "Completed",
    color:"blue",
    time: "Project Y",
    days: "11",
    done: true,
  },
  {
    id: 5,
    status: "Delivered",
    color:"yellow",
    time: "Project Z",
    days: "1",
    done: false,
  },
];
